# Generated by Django 5.1 on 2025-09-12 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 639-1 (2 letras).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2,5}$', "Use código ISO 639-1, p. ej. 'es'.")])),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 4217 (3 letras).', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}$', "Use código ISO 4217, p. ej. 'CLP'.")])),
                ('nombre', models.CharField(max_length=30)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 3166-1 alpha-2 (2 letras).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', "Use código ISO 3166-1 alpha-2, p. ej. 'CL'.")])),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='libroficha',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='autor_prologo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='codigo_imagen',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='descuento_distribuidor',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Porcentaje de 0.0 a 99.9', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.9)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ean',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='grosor_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ilustrador',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_edicion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_impresion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_paginas',
            field=models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='peso_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='rango_etario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='resumen_libro',
            field=models.TextField(default='sin resumen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='tematica',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='traductor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='autor',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='fecha_edicion',
            field=models.DateField(db_index=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='isbn',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='titulo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='idioma_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.idioma'),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.moneda'),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='pais_edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.pais'),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='tipo_tapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipotapa'),
        ),
        migrations.AddIndex(
            model_name='libroficha',
            index=models.Index(fields=['isbn'], name='catalogo_li_isbn_e23631_idx'),
        ),
        migrations.AddIndex(
            model_name='libroficha',
            index=models.Index(fields=['titulo'], name='catalogo_li_titulo_5d8407_idx'),
        ),
        migrations.AddIndex(
            model_name='libroficha',
            index=models.Index(fields=['autor'], name='catalogo_li_autor_5bbf04_idx'),
        ),
        migrations.AddIndex(
            model_name='libroficha',
            index=models.Index(fields=['fecha_edicion'], name='catalogo_li_fecha_e_6f1ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='libroficha',
            index=models.Index(fields=['editorial'], name='catalogo_li_editori_3f16c2_idx'),
        ),
    ]
