# Generated by Django 5.1 on 2025-09-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_add_tipo_tapa_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroficha',
            name='idioma_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.idioma'),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.moneda'),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='pais_edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.pais'),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='tipo_tapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipotapa'),
        ),
    ]
