# Generated by Django 5.2.5 on 2025-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True # Indicamos que esta es la migración inicial de la app

    dependencies = [
        # Dependemos del modelo de usuario definido en settings.AUTH_USER_MODEL
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Creamos el modelo Editorial
        migrations.CreateModel(
            name='Editorial',
            fields=[
                # Usamos BigAutoField como clave primaria
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Campo obligatorio para el nombre de la editorial
                ('nombre', models.CharField(max_length=150)),
                # Campo opcional para el identificador fiscal
                ('id_fiscal', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),

        # Creamos el modelo Profile, que amplía el modelo de usuario
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Definimos el rol con choices y valor por defecto "CONSULTOR"
                ('role', models.CharField(choices=[('EDITOR', 'Editor'), ('CONSULTOR', 'Consultor'), ('ADMIN', 'Admin')], default='CONSULTOR', max_length=20)),
                 # Relacionamos 1 a 1 con el modelo de usuario
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),

        # Creamos el modelo intermedio UsuarioEditorial
        migrations.CreateModel(
            name='UsuarioEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Relacionamos con una Editorial (muchos a uno)
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.editorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de editorial',
                'verbose_name_plural': 'Usuarios de editorial',
                # Restringimos para que no se duplique la combinación usuario-editorial
                'constraints': [models.UniqueConstraint(fields=('user', 'editorial'), name='unique_usuario_editorial')],
            },
        ),
    ]
